version: 2

sources:
  - name: external_source
    meta:
      external_location: "{{ env_var('TRANSFORM_S3_PATH_INPUT') }}"
    tables:
      - name: pypi_file_downloads


tests:
  - test: "{{ env_var('TRANSFORM_S3_PATH_INPUT') }}"